@startuml sample

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

' m**はマスタテーブル, それ以外はトランザクションテーブルです
' 各idはintじゃないほうが良いかも

' PlantUML (VS Coode拡張機能 jebbs.plantuml) setting.json
' {
'     "window.zoomLevel": 1,
'     "workbench.colorTheme": "Solarized Dark",
'     "plantuml.commandArgs": [
'         "-Xmx2g", "-DPLANTUML_LIMIT_SIZE=16384"
'     ],
'     "plantuml.server": "https://www.plantuml.com/plantuml",
'     "plantuml.render": "PlantUMLServer"
' }
' 参考
' https://plantuml.com/ja/ie-diagram

entity "User" as User {
    - user_id : int NOT NULL
    --
    * name : varchar(255)
    * email : varchar(255)
    * password : varchar(255)
    * total_time : int 
        'ユーザーの総学習時間
    created_at : datetime
    * updated_at : datetime
}

entity "Course" as Course {
    - course_id : int NOT NULL
    --
    - user_id : int <<FK>>
    - m_course_id : int <<FK>>
    --
    * total_time : int
        ' コース内コンテンツの学習時間の合計
    * achievement_rate : int
        ' コース内コンテンツの完了した割合
    created_at : datetime
    * updated_at : datetime
}

entity "Content" as Content {
    - content_id : int NOT NULL
    --
    - course_id : int <<FK>>
    - m_content_id : int <<FK>>
    --
    * learning_time : int
        ' コンテンツの総学習時間
    * complete_flag : int
        ' 完了(1) or 未完了(0)
    created_at : datetime
    * updated_at : datetime
}

entity "mCourse" as mCourse {
    - m_course_id : int NOT NULL
    --
    * name : varchar(255)
    created_at : datetime
    * updated_at : datetime
}

entity "mContent" as mContent {
    - m_content_id : int NOT NULL
    --
    * name : varchar(255)
    created_at : datetime
    * updated_at : datetime
}


entity "Category" as Category {
    - category_id : int NOT NULL
    --
    - m_category_id : int <<FK>>
    --
    created_at : datetime
    * updated_at : datetime
}

entity "mCategory" as mCategory {
    - m_category_id : int NOT NULL
    --
    * name : varchar(255)
        ' ex 初心者向け, Python, コラム
    created_at : datetime
    * updated_at : datetime
}

entity "Src" as Src {
    - src_id : int NOT NULL
    --
    - content_id : int <<FK>>
    --
    * name : varchar(255)
    * text : blob
         ' ソースコードの内容(バイナリ)
         ' base64でも可?
    created_at : datetime
    * updated_at : datetime    
}

entity "mSrc" as mSrc {
    - m_src_id : int NOT NULL
    --
    - m_content_id : int <<FK>>
    --
    * text : blob
         ' サンプルコード 
         ' ソースコードの内容(バイナリ)
         ' base64でも可?
    created_at : datetime
    * updated_at : datetime    
}

entity "PlateauModel" as PlateauModel {
    - plateau_model_id : int NOT NULL
    --
    - content_id : int <<FK>>
    --
    * name : varchar(255)
    * model_data : blob
         ' 3Dモデルファイル(バイナリ)
         ' base64でも可?
         ' ファイルパスでも可(3Dtiles読み出しなど)
    created_at : datetime
    * updated_at : datetime    
}

entity "mPlateauModel" as mPlateauModel {
    - m_plateau_model_id : int NOT NULL
    --
    - m_content_id : int <<FK>>
    --
    * name : varchar(255)
    * model_data : blob
         ' 3Dモデルファイル(バイナリ)
         ' base64でも可?
         ' ファイルパスでも可(3Dtiles読み出しなど)
    created_at : datetime
    * updated_at : datetime    
}



User ||..o{ Course
Course ||--|{ Content
Course ||--|{ Category
mCourse ||--|{ Course
mContent ||--|{ Content
mCategory ||--|{ Category
Content ||--|| Src
mSrc ||--|{ Src
Content ||--|| PlateauModel
mPlateauModel ||--|{ PlateauModel

@enduml